### PR TITLE
Add package.json

### PR DESCRIPTION
**Pull request by rarila**
I created a basic package.json to make this software (hopefully:-) work with ``npm``. It probably also would be a good idea to tag a release. Thanks a lot!

### CODE REVIEW

**Comment by appastair** [comment]
@rarila; the project maintainer (@addywaddy) - seems inactive. :no_mouth:

**Comment by rarila** [comment]
@appastair yeah, was afraid of that, but giving it a try did cost only a few minutes.

**Comment by godspeed1715** [comment]
@rarila I have included your ideas into my fork of this project. Check it out if you are interested. I also added a few features I thought were useful.
https://github.com/godspeed1715/jquery.tagcloud.js

**Comment by addywaddy** [comment]
Hi @rarila Sorry for the delay. Looks good!

**Pull request merged**
